package constructors;

public class ConstructorsDemo1 {
	
	
	/*// default constructor
	 * ConstructorsDemo1(){
	 * 
	 * }
	 */
	
	public static void main(String[] args) {
		
		ConstructorsDemo1 obj=new ConstructorsDemo1();
		
		
	}

}


/*
Constructor:
=============
Constructors are used to initialize the values to instance variables at the time of object creation.

Rules:
1. Constructor name and class name must be same.
2. Access modifiers are applicable for constructor (public, private, protected, default)
3. Parameters can be passed to the constructor.
4. Return type concept is not applicable.

syntax:
[access_modifier] classname([paramslist]){
--
---
--
}


2 types:

1. Default constructor:
If we have not declared at least one constructor, then jvm will create 0-arg constructor with empty implementation.
the constructor generated by compiler is called default constructor.
default constructor is 0-arg or no-arg constructor.

2. User defined constructor:

The constructor declared by the user explicitly is called user defined constructor.
	
	i. 0-arg or no-arg constructor
	ii. parameterized constructor





*/